#!/bin/bash
#
# This script runs the virtual python environment.  This depends on the
# vars file like setup-django. Please run this in the same folder
# as the .vpython-vars file!  We can't make it a global file...

# Go into the dir that we want to run this from.
len=`expr length $(basename $0)`
sauce_dir=${0:0:-$len}

VARS_FILE="$sauce_dir/.vpython-vars"
GLOB_FILE="$sauce_dir/.vpython-globals"

if [ -e $VARS_FILE ]; then
  . $VARS_FILE
else
  echo "ERROR: $VARS_FILE not found. File needed for variables."
  exit 1
fi

echo 'Entering virtual python environment.  Fear not, peasant!'
echo 'Simply hit CTRL-D or type the "exit" command to exit.'
echo "Trust me. You'll be fine."

# Setup the environment!
/bin/bash 
